# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  oc_username: ${{ secrets.OC_USERNAME }}
  oc_password: ${{ secrets.OC_PASSWORD }}
  oc_browser: ${{ vars.OC_BROWSER }}
  oc_url: ${{ vars.OC_URL }}

jobs:
# Job 1 - Maven build and run testcases
  build:
    runs-on: macos-latest
    steps:
    - name: Step 1 - Checkout the project
      uses: actions/checkout@v4
      
    - name: Step 2 - Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Print some info
      run: |
        echo "printing ..."
        echo "Runner OS: " $ImageOS
        echo "Browser: " ${{ vars.OC_BROWSER }}
        echo "Url: " ${{ vars.OC_URL }}
        
    - name: Step 3 - Install Chrome browser
      if: ${{env.oc_browser == 'chrome'}}
      uses: browser-actions/setup-chrome@v1
      # with:
      #   chrome-version: 134
      #   install-chromedriver: true
    - name: Step 3 - Install Edge browser
      if: ${{env.oc_browser == 'edge'}}
      uses: browser-actions/setup-edge@v1
       # firefox browser throwing org.openqa.selenium.SessionNotCreatedException even in headless mode
       
    - name: Step 4 - Build with Maven
      # run: mvn -B package --file pom.xml
      run: mvn test -Dtest=LoginTest#verifyLogin
      # run: mvn clean test
      
    - name: Step 5 - Archive report and log files
      uses: actions/upload-artifact@v4
      with:
        name: upload-extentReport-log
        path: |
          test-output/extent/extentReport.html
          applogs/app.log

# Job 2 - sending test artifacts over email
  Send-Email:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Download Test artifacts
        uses: actions/download-artifact@v2
        with:
          name: upload-extentReport-log
          path: test-artifacts

      - name: Send email with Test artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Selenium test results for ${{ github.repository }} ${{ github.sha }}"
          from: Test Suite
          body: |
            Hi,
            The maven build workflow for ${{ github.repository }} ${{ github.sha }} has completed.
            Please find the test artifacts attached to this email.
            
            Regards!!
          to: nikhildave75@gmail.com
          attachments: |
            ./test-artifacts/*.html
            ./test-artifacts/*.log
